config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :conversations
  resources :personal_messages
  resources :users

  mount ActionCable.server => '/cable'

  root to: 'conversations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  has_many :personal_messages, -> { order(position: :asc) }, dependent: :destroy

  validates :author, uniqueness: {scope: :receiver}

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id =?)", user.id, user.id)
  end

  def participates?(user)
    author == user || receiver == user
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)
  end
end

app/models/personal_message.rb
class PersonalMessage < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  acts_as_list scope: :conversation

  validates :body, presence: true

  after_create_commit do
    conversation.touch
    NotificationBroadcastJob.perform_later(self)
  end

  def receiver
    if conversation.author == conversation.receiver || conversation.receiver == user
      conversation.author
    else
      conversation.receiver
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :personal_messages, dependent: :destroy

  def online?
    !Redis.new.get("user_#{self.id}_online").nil?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation
  before_action :check_participating!, except: [:index]

  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @personal_message = PersonalMessage.new
    @conversations = Conversation.participating(current_user)
  end

  private

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

end

app/controllers/personal_messages_controller.rb
class PersonalMessagesController < ApplicationController
  before_action :check_receiver!, only: [:new, :create]

  def new
    redirect_to conversation_path(@conversation) and return if @conversation
    @personal_message = current_user.personal_messages.build
  end

  def create
    @conversation ||= Conversation.create(author_id: current_user.id,
                                         receiver_id: @receiver.id)
    @personal_message = current_user.personal_messages.build(personal_message_params)
    @personal_message.conversation_id = @conversation.id
    @personal_message.save!

    flash[:success] = "ok!"
    redirect_to conversation_path(@conversation)
  end

  private

  def personal_message_params
    params.require(:personal_message).permit(:body)
  end

  def check_receiver!
    @receiver = User.find_by(id: params[:receiver])
    redirect_to(root_path) and return unless @receiver
    @conversation = Conversation.between(current_user.id, @receiver.id)[0]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/_conversation.html.erb
<div>
  From <strong><%= conversation.author.email %></strong> to
  <strong><%= conversation.receiver.email %> (<%= conversation.receiver.online? ? 'online' : 'offline' %>)</strong>
  <br>
  <%= link_to 'View conversation', conversation_path(conversation) %>
  <hr>
</div>

app/views/conversations/index.html.erb
<h1>Your conversations</h1>

<p><%= link_to 'Start conversation', new_personal_message_path %></p>

<div id="conversations">
  <%= render @conversations %>
</div>

app/views/conversations/index.js.erb
$('#conversations').replaceWith('<%= j render @conversations %>');

app/views/conversations/show.html.erb
<h1>To <%= @conversation.receiver.email %></h1>

<div class="group">
  <div id="conversations-sidebar">
    <h2>Your conversations</h2>

    <%= render @conversations %>
  </div>

  <div id="conversation-main">
    <div id="conversation-body" data-conversation-id="<%= @conversation.id %>">
      <%= render partial: 'personal_messages/personal_message',
                 collection: @conversation.personal_messages,
                 locals: {personal_message: :personal_mesage} %>
    </div>

    <%= form_for @personal_message, url: '#', html: {class: 'async-conversation'} do |f| %>
      <%= hidden_field_tag 'conversation_id', @conversation.id %>
      <%= f.label :body %>
      <%= f.text_area :body %>

      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>PersonalChat</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

<% if user_signed_in? %>
  <div id="current-user" data-id="<%= current_user.id %>"></div>
  <p><%= link_to 'Conversations', root_path %> | <%= link_to 'Users', users_path %></p>
  <p>
    Logged in as <%= current_user.email %>
    <%= link_to 'Log Off', destroy_user_session_path, method: :delete %>
  </p>
<% end %>

<%= yield %>
</body>
</html>

app/views/notifications/_notification.html.erb
<div id="notification">
  <div class="close">close me</div>
  <p>
    <%= message.body %><br>
    from <%= message.user.email %>
  </p>
  <p><%= link_to 'Take me there now!', conversation_path(message.conversation) %></p>
</div>

app/views/personal_messages/_personal_message.html.erb
<p><%= personal_message.body %></p>
<p>at <strong><%= personal_message.created_at %></strong><br>
  by <strong><%= personal_message.user.email %></strong></p>
<hr>

app/views/personal_messages/new.html.erb
<h1>New message to <%= @receiver.email %></h1>

<%= form_for @personal_message do |f| %>
  <%= hidden_field_tag 'receiver', @receiver.id %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/users/_user.html.erb
<li><%= link_to user.email, user_path(user) %></li>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <%= render @users %>
</ul>

app/views/users/show.html.erb
<h1>Profile of <%= @user.email %></h1>

<p><%= link_to 'Write him a message', new_personal_message_path(receiver: @user.id) %></p>